/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNI */

#ifndef _Included_jni_JNI
#define _Included_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNI
 * Method:    dajSpravu
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_JNI_dajSpravu
  (JNIEnv *, jclass);

/*
 * Class:     jni_JNI
 * Method:    posliSpravu
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_JNI_posliSpravu
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
